# This is a basic workflow to publish a Twilio function with Github Actions

name: Twilio CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      # Runs a single command using the runners shell
      - name: Install dependencies for the twilio function
        run: npm ci
      # added by JFL
      - name: create env file
        run: |
         touch .env
         echo TWILIO_ACCOUNT_SID=${{ secrets.TWILIO_ACCOUNT_SID }} >> .env
         echo TWILIO_API_KEY_SID=${{ secrets.TWILIO_API_KEY_SID }} >> .env
         echo TWILIO_API_KEY_SECRET=${{ secrets.WILIO_API_KEY_SECRET }} >> .env
         echo TWILIO_AUTH_TOKEN=${{ secrets.TWILIO_AUTH_TOKEN }} >> .env
         echo REACT_APP_DISABLE_TWILIO_CONVERSATIONS=true >> .env
      - run: CI=false npm run build
      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: /opt/bitnami/twilio-video-app-react
          remote_host: ec2-50-18-145-191.us-west-1.compute.amazonaws.com
          remote_user: bitnami
          remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"
      # - name: Install twilio cli and run deploy command
       # env:
         # TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
         # TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
         # TWILIO_API_SECRET: ${{secrets.TWILIO_API_SECRET}}
        # Install the Twilio CLI and the serverless plugin then deploy the function
        # run: npm install twilio-cli -g && twilio plugins:install @twilio-labs/plugin-rtc && npm run deploy:twilio-cli -- --override
        
